class AssertionViolatedException
!!!3901851.java!!!	AssertionViolatedException()
		super();
!!!3901979.java!!!	AssertionViolatedException(in message : String)
		super(message = "INTERNAL ERROR: "+message); // Thanks to Java, the constructor call here must be first.
		detailMessage=message;
!!!3902107.java!!!	extendMessage(in pre : String, in post : String) : void
		if (pre  == null) pre="";
		if (detailMessage == null) detailMessage="";
		if (post == null) post="";
		detailMessage = pre+detailMessage+post;
!!!3902235.java!!!	getMessage() : String
		return detailMessage;
!!!3902363.java!!!	_main(in args : String) : void
		AssertionViolatedException ave = new AssertionViolatedException("Oops!");
		ave.extendMessage("\nFOUND:\n\t","\nExiting!!\n");
		throw ave;
!!!3902491.java!!!	getStackTraceAsStr() : String
		return Utility.getStackTrace(this);
